lib/percy/capybara/loaders/sprockets_loader.rb
asset pipeline can raise `Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError`
or similar when the asset is not precompiled
but the real asset path is not really needed to skip files based on extension
=> do not ask asset pipeline for skipped resources

spec/lib/percy/capybara/client/builds_spec.rb, spec/lib/percy/capybara/client/snapshots_spec.rb
When running specs from my forked repo (mfazekas/percy-capybara) i get error like this:
```ruby
7) Percy::Capybara::Client::Builds#initialize_build initializes and returns a build
Failure/Error: @current_build = client.create_build(client.config.repo, options)
WebMock::NetConnectNotAllowedError:
Real HTTP connections are disabled. Unregistered request: POST https://percy.io/api/v1/repos/mfazekas/percy-capybara/builds/ with body '{"data":{"type":"builds","attributes":{"branch":"master","target-branch":null,"commit-sha":"06f42b96337e8f9d9b97427a919969a835e4e750","commit-committed-at":"2016-10-12 11:12:58 -0700","commit-author-
```
The patch replaces ```https://percy.io/api/v1/repos/percy/percy-capybara/builds/``` with ```https://percy.io/api/v1/repos/#{Percy::Client::Environment.repo}/builds …
```
=> Make specs pass on forked repos

lib/percy/capybara/loaders/native_loader.rb, spec/lib/percy/capybara/client/testdata/test-localtest-me-images.html, spec/lib/percy/capybara/loaders/native_loader_spec.rb, spec/spec_helper.rb
Fixes: #8 
When running percy against non localhost/127.0.0.1/0.0.0.0 url, percy.io was missing css, and img resources. (We want to use percy to check staging, so test non local service, but some might be just using other alias to localhost like localtest.me)
It works by using capybara's current_url, and is a resource is coming from same scheme/host/port then we're just using the path for uploading (bug for downloading we're still using the full url). So before a resource was referred as ```http://localhost/css/imports.css``` now it's just ```/css/imports.css```
=> Support for nonlocal hosts.

lib/percy/capybara/client.rb, lib/percy/capybara/client/builds.rb, lib/percy/capybara/loaders/native_loader.rb, spec/lib/percy/capybara/client/builds_spec.rb, spec/lib/percy/capybara_spec.rb
Prevent several warnings:
* Initialize @failed variable before it's used
* build_initialized? now returns false if @current_build isn't defined 
* Remove calculation of sha in 2 places it's not used
* Remove setting of host_port where the variable isn't used
* Remove setting of capybara_client in specs where it's not used.
=> Prevent several warnings

lib/percy/capybara/client.rb, spec/lib/percy/capybara/client_spec.rb, spec/lib/percy/capybara_spec.rb
@fotinakis Change made, and specs updated.
I guess this also enables it in unknown CI providers.  I suspect this is okay as it'll still require the customer to specify the key and project in the environment, and they will have seen that their provider isn't in the list of supported ones.  I'd like your sanity check on this though.  :)
=> Enable by default, disable if PERCY_ENABLE=0

lib/percy/capybara/loaders/base_loader.rb, spec/lib/percy/capybara/loaders/base_loader_spec.rb
Fixes tests which die with:
```
Capybara::Poltergeist::FrameNotFound:
The frame '' was not found.
```
=> Fix bug with poltergeist frame handling.

lib/percy/capybara/loaders/base_loader.rb
For one user, sometimes this happens:
```
undefined method `client' for Percy:Module (NoMethodError)
```
When they use a custom loader like:
```ruby
require 'percy/capybara/loaders/sprockets_loader'
class CustomLoader < Percy::Capybara::Loaders::SprocketsLoader
...
end
Percy::Capybara.use_loader(CustomLoader)
Percy::Capybara.initialize_build
at_exit  { Percy::Capybara.finalize_build }
```
=> Fix module path import loading issues.

lib/percy/capybara/loaders/filesystem_loader.rb, spec/lib/percy/capybara/client/builds_spec.rb, spec/lib/percy/capybara/client/snapshots_spec.rb, spec/lib/percy/capybara/client_spec.rb, spec/lib/percy/capybara/loaders/filesystem_loader_spec.rb, spec/lib/percy/capybara/loaders/native_loader_spec.rb
In the filesystem loader, if baseurl was set to `/` or had a trailing slash like `/url-prefix/`, it would create URLs like `/url-prefix//index.html` which would break rendering. This fixes that bug.
=> Fix double-slash bug when baseurl is set to /.

.rubocop.yml, Gemfile, lib/percy/capybara/loaders/native_loader.rb, lib/percy/capybara/loaders/sprockets_loader.rb, percy-capybara.gemspec, spec/lib/percy/capybara/loaders/native_loader_spec.rb, spec/lib/percy/capybara/loaders/sprockets_loader_spec.rb, spec/support/test_helpers.rb
Closes: #10 
FYI Rails 5.1.0.rc1 seems to be default to sprockets 4
=> Sprockets 4 support for rails 5 & 5.1

lib/percy/capybara/client/builds.rb, spec/lib/percy/capybara/client/builds_spec.rb
Something we should have been doing all along:
Considered adding a way to disable this logging, but we can always add that later as a backwards-compatible config setting.
=> Add console output notification for builds.

lib/percy/capybara/client.rb, spec/lib/percy/capybara/client_spec.rb
I ran into this issue as we're in the process of removing Sprockets from our Rails application. I also looks like someone else had this [issue](https://github.com/percy/percy-capybara/issues/18) at some point.
AppVeyor is failing but it seems unrelated to these changes, doesn't look like it's configured?
=> Check to see if Sprockets::Rails is defined

.rubocop.yml
Looks like this just needs a gentle bump to make tests pass again.
=> Bump target ruby version to make rubocop happy

Gemfile, lib/percy/capybara/anywhere.rb, lib/percy/capybara/client.rb, lib/percy/capybara/client/builds.rb, percy-capybara.gemspec, spec/lib/percy/capybara/client/builds_spec.rb, spec/lib/percy/capybara/client/snapshots_spec.rb, spec/lib/percy/capybara/client_spec.rb, spec/support/test_helpers.rb
Removes checks for `PERCY_PROJECT` to enable support for the new token only build creation endpoint.
Note: this will be updated with the new `percy-client` gem before it is shipped.
https://github.com/percy/percy-client/pull/39
=> Update to token only build creation endpoint

.circleci/config.yml
Ruby 2.2 is EOL, and Ruby 2.3 will be EOL by the end of this month (see: https://www.ruby-lang.org/en/downloads/branches/). Remove them from our CI configuration, and add Ruby 2.5 instead. (We also run our CI on `ruby-latest`, which is currently 2.6.x.)
=> Remove Ruby 2.2 and 2.3 from CI configuration. Add Ruby 2.5

lib/environment.rb
This is an attempt to fix the error:
```
Failure/Error: Percy.snapshot(page)
NameError:
uninitialized constant Percy::VERSION
```
That I got trying to use the `4.0.0.pre.beta1` version of the Gem.
=> Import version file into environment.rb

lib/percy.rb, package.json, spec/lib/percy/percy_spec.rb
Looks like the key that was being passed isn't using the right casing for `@percy/agent`. `enableJavascript` is deprecated and apparently doesn't work. `enableJavaScript` is the correct way and does work. 
What's a good test for this that would surface JS not working in a snapshot? Probably introduce our own page?
=> fix: Enable JavaScript for builds

percy-capybara.gemspec
Purpose:
- Add useful links to <https://rubygems.org/gems/percy-capybara>.
- Expect useful integrations with 3rd-party tools (e.g. Dependabot).
See also:
- https://guides.rubygems.org/specification-reference/#metadata
=> Add metadata to gemspec

lib/percy.rb
This PR adds a rescue to catch the error log when the health check fails. If the health check fails we'll never capture snapshots so it's super helpful to know why it's failing.
=> fix: Add log if the health check endpoint fails

lib/percy.rb
If you're running your test suite without percy started, these health check logs would be very noisy and annoying. This PR will make it so they only log if you're setting the log level to `debug`.
=> fix: Only log healthcheck fail when `LOG_LEVEL=debug` is set

lib/environment.rb
If other version.rb files are in the load path, then it'll load them
instead leading to fun conflicts (error message in Rails is along the
lines of: `Unable to autoload constant VERSION...`)
This requires the Percy version file specifically. I believe other gems
have solved this by using a subfolder under `/lib` that contains the Gem
name rather than adding generic files in `lib` to the load path which
might cause more fun errors in future :) Happy to send a PR with that
change too if you'd like!
=> Require Percy version file specifically

lib/percy.rb, spec/lib/percy/percy_spec.rb
Adds the `requestHeaders` option for agent so we can pass request headers for asset-discovery.
=> feat: Add request headers option for asset discovery

lib/percy.rb, spec/spec_helper.rb
This will allow for proper serialization of iframes since that relies on checking for `enable_javascript` (`enableJavaScript`) being passed when capturing the DOM.
=> fix: pass options to DOM capture

.circleci/config.yml, lib/environment.rb, lib/percy.rb, spec/lib/percy/environment_spec.rb
This PR makes it possible (for sure) to use this package outside of Capybara (by eliminating the only Capybara specific method `evaluate_script`). In the future this package will likely be deprecated for a pure selenium ruby package (since this SDK implements nothing specific to Capybara). 
This adds Capybara's version reporting to our UA and also checks to see if Capybara is being used. For some reason, it seems like Capybara wraps WebDriver's `execute_script` method and it doesn't return its value. If Capybara is being used, we'll use their `evaluate_script` method. Otherwise, we'll use the `execute_script` method like _all the other selenium SDKs_.
=> fix: Use `execute_script` over `evaluate_script`

lib/percy.rb
Hot on the heels of #147... Turns out you can prepend the JS with `return` and it will return 🙃(FWIW, other web drivers implicitly return the value)
=> fix: Remove check for Capybara version

lib/percy.rb
The DOM won't return from `execute_script` if it's wrapped in an IIFE. This only wraps an IIFE around `evalaute_script`
=> fix: Only wrap `evaluate_script` calls in IIFE

percy-capybara.gemspec
According to this blog post the load path stuff we were doing in the gemspec is old hat: https://piotrmurach.com/articles/writing-a-ruby-gem-specification/
> This was a popular method to load a version file during the 1.8.7 and 1.9.2 Ruby era. It still remains popular, for example, for loading binary files. However, we can do better now. That’s where the require_relative method comes handy. It will load a file relative to the current location. Exactly what we need. All the three lines can be replaced in one fell swoop with:
When installing the beta into the example app I got an error about loading the VERSION module -- this should fix the issue.
=> 🐛  Use `require_relative` for ::VERSION

lib/percy/capybara.rb, percy-capybara.gemspec
I missed requiring the version file into the capybara file in #164. This also updates the included/distributed files in the gemspec file (removes tests files & includes the version file)
=> 🐛  require `version` in `percy/capybara`

lib/percy/capybara.rb, spec/lib/percy/percy_capybara_spec.rb
Big oof, when building the SDK I forgot to pass the rest of the options to the`snapshot` endpoint. It had 100% coverage..! 😐 Will close #169
=> 🐛  Pass snapshot options

README.md
This PR adds the `@percy/migrate` upgrade instructions to the README
=> 📝  Add `@percy/migrate` instructions to README

percy-capybara.gemspec, spec/spec_helper.rb
According to this issue the fix has been merged into capybara but hasn't been released yet. https://github.com/teamcapybara/capybara/issues/2511
This will fix tests failing since the deprecation pops up in the log output, which we're asserting against
=> ✅ Silence selenium warning coming from Capybara
